version: '3'
services:

  db:
    image: postgres:14.8-alpine
    container_name: db_app
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: 'django_drf'
      POSTGRES_PASSWORD: 12345
      PGDATA: /var/lib/postgresql/data/pgdata

  django_drf:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8002:8000'
    depends_on:
      - db
    env_file:
      - .env

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    restart: always
    depends_on:
      - django_drf
    volumes:
      - ./redis.conf:/etc/redis/redis.conf

  celery-beat:
    build: .
    command: celery -A config beat -l info
    depends_on:
      - redis
      - django_drf


