# Generated by Django 4.2.4 on 2023-09-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='course')),
                ('preview_img', models.ImageField(blank=True, null=True, upload_to='course/', verbose_name='preview')),
                ('description', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='lesson')),
                ('preview_img', models.ImageField(blank=True, null=True, upload_to='lessons/', verbose_name='preview')),
                ('description', models.TextField(verbose_name='description')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='video url')),
            ],
            options={
                'verbose_name': 'lesson',
                'verbose_name_plural': 'lessons',
            },
        ),
    ]
