# Generated by Django 4.2.4 on 2023-09-08 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('id',), 'verbose_name': 'course', 'verbose_name_plural': 'courses'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('id',), 'verbose_name': 'lesson', 'verbose_name_plural': 'lessons'},
        ),
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(to='lessons.lesson', verbose_name='lessons_in_course'),
        ),
        migrations.AddField(
            model_name='course',
            name='user_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_created'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='courses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.course', verbose_name='course'),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_payment', models.DateField(auto_now_add=True, verbose_name='date_of_payment')),
                ('summ', models.IntegerField(verbose_name='summ')),
                ('method_of_payment', models.CharField(choices=[('cash', 'Cash'), ('remittance', 'Remittance')], max_length=15, verbose_name='method_of_payment')),
                ('payed_course', models.ManyToManyField(blank=True, null=True, to='lessons.course', verbose_name='payed_course')),
                ('payed_lesson', models.ManyToManyField(blank=True, null=True, to='lessons.lesson', verbose_name='payed_lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
