# Generated by Django 4.2.4 on 2023-09-10 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_course_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lessons',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='payed_course',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='payed_lesson',
        ),
        migrations.AddField(
            model_name='payments',
            name='payed_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.course', verbose_name='payed_course'),
        ),
        migrations.AddField(
            model_name='payments',
            name='payed_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.lesson', verbose_name='payed_lesson'),
        ),
    ]
