# Generated by Django 4.2.4 on 2023-09-13 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0004_alter_payments_options_lesson_users_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user_course',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='users_lesson',
        ),
        migrations.AddField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='course_owner'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='lesson_owner'),
        ),
    ]
