# Generated by Django 4.2.4 on 2023-09-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_coursesubscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesubscriptions',
            name='status',
            field=models.BooleanField(verbose_name='status'),
        ),
    ]
