# Generated by Django 4.2.4 on 2023-09-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='method_of_payment',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], max_length=15, verbose_name='method_of_payment'),
        ),
    ]
