# Generated by Django 4.2.4 on 2023-09-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_remove_payments_payed_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='price_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='stripe_price_id'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='stripe_payment_id'),
        ),
    ]
