# Generated by Django 4.2.4 on 2023-09-20 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_payments_price_id_alter_payments_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='price_id',
        ),
    ]
