# Generated by Django 4.2.4 on 2023-09-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_remove_payments_payment_id_remove_payments_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='payment_id'),
        ),
    ]
